# Generated by Django 3.1.3 on 2021-02-19 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0006_auto_20210218_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('mobile', models.CharField(max_length=120)),
                ('whatsapp_number', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('photo', models.FileField(upload_to='CustomerProfileImages/')),
            ],
        ),
        migrations.CreateModel(
            name='MyRides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_status', models.CharField(choices=[('ongoing', 'ONGOING'), ('completed', 'COMPLETED'), ('canceled', 'CANCELED'), ('upcoming', 'UPCOMING')], max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('canceled', models.BooleanField(default=False)),
                ('review', models.CharField(max_length=1200)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.bikedetails')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customerprofile')),
            ],
        ),
    ]
