# Generated by Django 3.1.3 on 2021-02-19 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myrides',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='myrides',
            name='start_date',
        ),
    ]
