# Generated by Django 3.1.3 on 2021-02-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20210219_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='myrides',
            name='ride_id',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
